services:
  db:
    build:
      context: ./infrastructure
      dockerfile: datastore/db/Dockerfile
    container_name: godepot-db
    environment:
      POSTGRES_DB: godepot
      POSTGRES_USER: godepot
      POSTGRES_PASSWORD: godepot
    ports:
      - "5432:5432"
    volumes:
      - godepot-postgres-data:/var/lib/postgresql/data

volumes:
  godepot-postgres-data:
